# Generated by Django 4.2 on 2023-04-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_orderform_date_orderform_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
