# Generated by Django 4.2 on 2023-04-18 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_employee_email_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderform',
            name='number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
