# Generated by Django 4.2 on 2023-05-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_client_code_alter_orderformline_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderform',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=255),
        ),
    ]
